# Generated by Django 3.2 on 2023-02-07 02:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20230206_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Nguyen Hoang Truong', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='token_permission_infor_user',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
