# Generated by Django 3.2 on 2023-02-07 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_phoneuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneuser',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phones', to=settings.AUTH_USER_MODEL),
        ),
    ]
