# Generated by Django 3.2 on 2023-02-07 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_phoneuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_permission_infor_user',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
