# Generated by Django 3.2 on 2023-02-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_user_token_permission_infor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
