# Generated by Django 3.2 on 2023-02-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneuser',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
