# Generated by Django 3.2 on 2023-03-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_phoneuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=False),
            preserve_default=False,
        ),
    ]
