# Generated by Django 3.2 on 2023-07-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyAction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyaction',
            name='list_selected_categorié',
        ),
        migrations.AddField(
            model_name='historyaction',
            name='list_selected_categories',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historyaction',
            name='list_selected_products',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historyaction',
            name='list_selected_sales',
            field=models.TextField(null=True),
        ),
    ]
