# Generated by Django 3.2 on 2023-03-13 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('private_key', models.CharField(max_length=1024)),
                ('public_key', models.CharField(max_length=1024)),
                ('created', models.DateTimeField()),
                ('expired', models.DateField()),
            ],
        ),
    ]
