# Generated by Django 3.2 on 2023-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decryptRSA', '0002_alter_deviceclient_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceclient',
            name='public_key',
        ),
        migrations.AlterField(
            model_name='deviceclient',
            name='private_key',
            field=models.TextField(),
        ),
    ]
