# Generated by Django 3.2 on 2023-03-13 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decryptRSA', '0003_auto_20230313_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceclient',
            name='public_key',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
