# Generated by Django 3.2 on 2023-03-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decryptRSA', '0006_deviceclient_date_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceclient',
            name='private_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
