# Generated by Django 3.2 on 2023-03-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decryptRSA', '0007_alter_deviceclient_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceclient',
            name='name_private_key',
            field=models.TextField(null=True),
        ),
    ]
