# Generated by Django 3.2 on 2023-02-23 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_heart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('price', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('receiver', models.CharField(max_length=50, null=True)),
                ('address_receiver', models.CharField(max_length=200, null=True)),
                ('phone_receiver', models.CharField(max_length=10, null=True)),
                ('status', models.BooleanField()),
                ('note', models.CharField(max_length=50, null=True)),
                ('logs', models.TextField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('cancel', models.BooleanField()),
                ('request_cancel', models.BooleanField()),
                ('transport_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.transport')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_orders', to='order.order')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
