# Generated by Django 3.2 on 2023-06-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_voucher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
