# Generated by Django 3.2 on 2023-02-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_product',
            name='data',
            field=models.ImageField(upload_to='media/photos/'),
        ),
    ]
