# Generated by Django 3.2 on 2023-04-07 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_product', '0001_initial'),
        ('product', '0003_heart'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='blog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearts', to='blog_product.blog'),
        ),
        migrations.AddField(
            model_name='heart',
            name='comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearts', to='blog_product.comment'),
        ),
        migrations.AddField(
            model_name='heart',
            name='type',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
