# Generated by Django 3.2 on 2023-04-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20230407_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Heart',
        ),
    ]
