# Generated by Django 3.2 on 2023-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_product', '0003_comment_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_email',
            field=models.CharField(default='cart1@gmail.com', max_length=200),
            preserve_default=False,
        ),
    ]
