# Generated by Django 3.2 on 2023-04-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_product', '0008_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isEdit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='isEdit',
            field=models.DateTimeField(null=True),
        ),
    ]
