# Generated by Django 3.2 on 2023-04-11 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_product', '0009_auto_20230411_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='isEdit',
            new_name='is_edit',
        ),
    ]
