# Generated by Django 3.2 on 2023-04-12 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_heart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_product', '0010_rename_isedit_comment_is_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heart',
            name='blog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearts', to='blog_product.blog'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearts', to='blog_product.comment'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearts', to='product.product'),
        ),
        migrations.AlterField(
            model_name='heart',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hearts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Media_Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_comments', to='blog_product.comment')),
            ],
        ),
    ]
