# Generated by Django 3.2 on 2023-04-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_product', '0011_auto_20230412_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media_comment',
            name='type',
            field=models.BooleanField(),
        ),
    ]
