# Generated by Django 3.2 on 2023-04-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_product', '0013_auto_20230412_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='information_customer',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_profile',
            field=models.CharField(max_length=500),
        ),
    ]
