# Generated by Django 3.2 on 2023-02-20 09:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_heart'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetailFlashSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_created', models.DateTimeField(auto_now=True)),
                ('datetime_finished', models.DateTimeField(blank=True)),
                ('status', models.BooleanField(blank=True)),
                ('flash_sale_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_flash_sale', to='flashSaleProduct.flashsale')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_flash_sale', to='product.product')),
            ],
        ),
    ]
