# Generated by Django 3.2 on 2023-02-23 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashSaleProduct', '0002_detailvoucher_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailvoucher',
            name='voucher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_voucher', to='flashSaleProduct.voucher'),
        ),
    ]
