# Generated by Django 3.2 on 2023-02-23 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashSaleProduct', '0003_detailvoucher_voucher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailvoucher',
            name='voucher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_vouchers', to='flashSaleProduct.voucher'),
        ),
    ]
