# Generated by Django 3.2 on 2023-03-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashSaleProduct', '0004_alter_detailvoucher_voucher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
