# Generated by Django 3.2 on 2023-03-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashSaleProduct', '0005_voucher_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='limited_price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
