# Generated by Django 3.2 on 2023-07-09 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashSaleProduct', '0006_voucher_limited_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailflashsale',
            name='flash_sale_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_flash_sales', to='flashSaleProduct.flashsale'),
        ),
    ]
